### ISSUE TITLE
Missing field 'dynamic weights' in the generated .syndrome files

### ISSUE THREAD

**Issue by zhangmy61** [yuewuo/fusion-blossom#23]
Hello,

When running the tests in ./benchmark/paper_fusion_circuit_level/decoding_latency_T, we encountered an error that says:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `dynamic_weights`", line: 1, column: 275)', src\example_codes.rs:1200:94

It refers to the absence of a 'dynamic weights' field in the generated ".syndrome" file. Therefore, we manually added the 'dynamic weights' part in these files and leave the content empty. Eventually these tests run successfully, and we obtain latency results close to the results in your paper. But we are still curious if the way we change the file affects the final results.

It would be great if you could check :>

**Comment by yuewuo** [comment]
Sorry for the inconvenience. It won't affect the results, but I'll fix this problem shortly. One quick solution is to delete the `.syndrome` file so that it will be regenerated the next time you run the script. The new version should include this field.

The `dynamic_weights` field is a new feature that allows users to update edge weights. Given the default value, it behaves exactly the same.

**Comment by yuewuo** [comment]
It has been fixed in the `dev` branch. Once the CI tests are passed, they will merge into the `main` branch. Thanks for reporting it!
